easy_admin:
    site_name: 'Admin: Wild Ciné'
    formats:
        date:     'd/m/Y'
    entities:
        Artist:
            class: App\Entity\Artist
            list:
                fields: ['name' , 'firstName' , 'birthDate' , 'biography' , 'picture' , 'sex']
            search:
                fields: ['name', 'firstName' , 'birthDate' , 'biography' , 'picture']
        Director:
            class: App\Entity\Director
        Genre:
            class: App\Entity\Genre
        Movie:
            class: App\Entity\Movie
        Serie:
            class: App\Entity\Serie
        User:
            class: App\Entity\User
            list:
                fields: ['email', 'roles', 'password']
    design:
        brand_color: '#BC8F8F'
        assets:
          favicon: '/assets/backend/favicon.png'
          css:
          - 'bundles/easyadmin/bootstrap-all.css'
          - 'css/admin.css'
          js:
          - 'bundles/easyadmin/bootstrap-all.js'
